use anchor_lang::prelude::*;
use arcium_anchor::prelude::*;
use arcium_macros::comp_def_offset;

use crate::errors::CerberusPokerError;
use crate::state::{GameSession, GameState, ShuffleComplete};

const COMP_DEF_OFFSET_SHUFFLE_DECK: u32 = comp_def_offset("shuffle_deck_demo");

/// Output type generated by Arcium from the `shuffle_deck` encrypted instruction.
/// The MXE returns Enc<Mxe, [u8; 52]> — the shuffled deck still encrypted for MXE.
/// We store the commitment hash on-chain to prevent deck substitution.
#[derive(AnchorDeserialize)]
pub struct ShuffleDeckOutput {
    /// The shuffled deck commitment hash (SHA-256 of the encrypted deck)
    /// This is the public output — the actual deck stays encrypted in MXE state
    pub deck_hash: [u8; 32],
}

pub fn handler(
    ctx: Context<ShuffleDeckCallback>,
    output: SignedComputationOutputs<ShuffleDeckOutput>,
) -> Result<()> {
    // Verify the MXE output signature — ensures result is authentic
    let result = match output.verify_output(
        &ctx.accounts.cluster_account,
        &ctx.accounts.computation_account,
    ) {
        Ok(out) => out,
        Err(e) => {
            msg!("MXE output verification failed: {}", e);
            return Err(CerberusPokerError::AbortedComputation.into());
        }
    };

    let game = &mut ctx.accounts.game_session;

    // Verify we're in the right state
    require!(game.state == GameState::Shuffle, CerberusPokerError::InvalidGameState);

    // Store the deck commitment hash on-chain
    // This prevents the deck from being swapped after shuffle
    game.encrypted_deck_hash = result.deck_hash;

    // Transition to Deal phase — deck is now shuffled and committed
    game.state = GameState::Deal;
    game.shuffle_deadline = 0; // Clear deadline

    let game_id = game.game_id;
    emit!(ShuffleComplete {
        game_id,
        deck_hash: result.deck_hash,
    });

    msg!(
        "Shuffle complete for game {}. Deck hash: {:?}",
        game_id,
        &result.deck_hash[..8] // log first 8 bytes only
    );

    Ok(())
}

#[callback_accounts("shuffle_deck_demo")]
#[derive(Accounts)]
pub struct ShuffleDeckCallback<'info> {
    pub arcium_program: Program<'info, Arcium>,

    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_SHUFFLE_DECK))]
    pub comp_def_account: Account<'info, ComputationDefinitionAccount>,

    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,

    #[account(
        mut,
        address = derive_cluster_pda!(mxe_account, CerberusPokerError::InvalidGameState)
    )]
    pub cluster_account: Account<'info, Cluster>,

    /// CHECK: computation_account, checked by the arcium program.
    pub computation_account: UncheckedAccount<'info>,

    /// The game session to update — passed as a custom callback account
    #[account(mut)]
    pub game_session: Account<'info, GameSession>,
}
